root: true
env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - off
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console:
    - off
  require-yield:
    - off
